services:
  ollama:
    volumes:
      - ./ollama:/root/ollama
      - volume-ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}
    ports:
      - 11434:11434
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]


  # litellm:
  #   image: ghcr.io/berriai/litellm:main-latest
  #   environment:
  #     - "MASTER_KEY=${LITELLM_API_KEY}"
  #     - "OPENAI_API_KEY=${OPENAI_API_KEY}"
  #     - "MISTRAL_API_KEY=${MISTRAL_API_KEY}"
  #     - "ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}"
  #   ports:
  #     - 4000:8000
  #   volumes:
  #     - ./litellm/config.yaml:/app/config.yaml
  #   command: [ "--config", "/app/config.yaml", "--port", "8000" ]
  #   restart: unless-stopped

  ollama-webui:
    build:
      context: .
      args:
        OLLAMA_BASE_URL: '/ollama'
      dockerfile: Dockerfile
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    container_name: ollama-webui
    volumes:
      - volume-ollama-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - ${OPEN_WEBUI_PORT-3000}:8080
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      # - WEBUI_SECRET_KEY=
      - WEBUI_AUTH=False
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

volumes:
  volume-ollama:
    name: volume-ollama
  volume-ollama-webui:
    name: volume-ollama-webui
